spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

  kafka:
    bootstrap-servers: ${KAFKA_URI}
    producer:
      bootstrap-servers: ${KAFKA_URI}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

client:
  id: ${CLIENT_ID}
  secret: ${CLIENT_SECRET}
  name: ${CLIENT_NAME}
  redirect-uri: ${REDIRECT_URI}
  tokenTTLInSeconds: ${TOKEN_TTL}

logging:
  level:
    org:
      springframework:
        security: warn